---
- name: keystore.yml | Make backup of KeyStore
  ansible.builtin.copy:
    src: "{{ keystore }}"
    dest: "{{ keystore }}.{{ ansible_facts['date_time']['epoch'] }}.bak"
    mode: '0600'
    owner: "unifi"
    remote_src: true

- name: keystore.yml | Create temporary P12 file
  ansible.builtin.tempfile:
    state: file
    suffix: .p12temp
  register: p12_temp

- name: keystore.yml | generate PKCS12 CSR
  ansible.builtin.command: |
    openssl pkcs12 -export
    -in {{ crt_full_path }}
    -inkey {{ key_full_path }}
    -CAfile {{ intermediate_full_path }}
    -out {{ p12_temp.path }} -passout pass:{{ keystore_password }}
    -caname root -name {{ unifi_alias }}

- name: keystore.yml | Stop service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: stopped

- name: keystore.yml | Delete the previous certificate data from keystore to avoid "already exists" message
  ansible.builtin.command: |
    keytool -delete
    -alias {{ unifi_alias }}
    -keystore {{ keystore }}
    -deststorepass {{ keystore_password }}

- name: keystore.yml | Import the temp PKCS12 file into the UniFi keystore
  ansible.builtin.command: |
    keytool -importkeystore
    -srckeystore {{ p12_temp.path }} -srcstoretype PKCS12
    -srcstorepass {{ keystore_password }}
    -destkeystore {{ keystore }}
    -deststorepass {{ keystore_password }}
    -destkeypass {{ keystore_password }}
    -alias {{ unifi_alias }} -trustcacerts

- name: keystore.yml | Import the certificate authority data into the UniFi keystore
  ansible.builtin.command: |
    java -jar {{ java_dir }}/lib/ace.jar
    import_cert {{ crt_full_path }} {{ intermediate_full_path }}
  when: service_name == "unifi"
